### ISSUE TITLE
using 24 distinct colors

### ISSUE THREAD

**Issue by housw** [xuechunxu/DiTing#3]
Hi Xuechun, 

would you like to use this set of colors instead: http://phrogz.net/tmp/24colors.html ? I have given it a try and it looks much nicer, but I'm not sure does the color order matter in the script `sketch.py`, I feel the color legend doesn't fit well with the sample color after changing to these 24 colors. 

So it would be great if you would like to officially modify it, much appreciated!

Best, 
Shengwei

**Comment by xuechunxu** [comment]
Very nice color scheme！I will update it soon.

Thanks for your suggestion.
Chunxu

**Comment by housw** [comment]
Awesome, thanks!

**Comment by xuechunxu** [comment]
Hi Shengwei,

I have updated the color scheme, which can be acquired through `git clone`. I have tested it and worked well. We will release it together with other changed functions using `conda` in the next version.

The color scheme is totally awesome!
![image](https://user-images.githubusercontent.com/23622076/122660790-c6883380-d1b6-11eb-9fc9-9a969b5692e6.png)

Cheers,
Chunxu

**Comment by housw** [comment]
Hi Chunxu, 

👍👍👍, thanks a lot! By the way, can you use all the 24 colors? I got an index out of range error using 22 samples. In the case of >24 samples, we probably need to cycle through the color list. 

Cheers, 
Shengwei

**Comment by xuechunxu** [comment]
Hi Shengwei,

I have updated the color scheme using all 24 colors. I think the sketch is difficult to be recognized when using so many samples.  If necessary, visualization can be executed independently, which allows users to adjust the final result table (e.g., merge some similar samples), and run:
`diting.py -vis <pathways_relative_abundance.tab>`

Enjoy,
Chunxu

**Comment by housw** [comment]
Cool, thanks a lot for the quick fix! Yes, I totally agree, I will close this thread for now.
