### ISSUE TITLE
How to handle "single or uneven" sequencing fastq files or add them to DiTing workflow?

### ISSUE THREAD

**Issue by MaryoHg** [xuechunxu/DiTing#32]
Dear developers,

Thanks for `diting.py`. 
I want to add my uneven reads (singles or those that lost their pair during QC-filtering) into DiTing workflow (or into `-r seqs/` folder). How do I need to rename uneven fastq files to `diting.py` to read them or include them into its workflow?

AFAIK both `megahit` and `metaspades.py` can deal and work with singles reads (using the `-r`/`-s`, respectively).

I dared to edit the `diting.py` script only to add the `--presets meta-large` option into `megahit` assembly process (I'm about to test if it worked out), however, to add single reads into the workflow might require heavy programming skills.

Thanks and regards,
Mar.

**Comment by SilentGene** [comment]
Hi Mar,

In this case, I suggest you assemble your reads independently suitable for your needs first. Then you can run DiTing by the command:
```bash
python diting.py -r <clean_reads_dir> -a <metagenomic_assembly> -o <output_dir>
```

Hope this helps.

Cheers,
Heyu

**Comment by MaryoHg** [comment]
Hello @SilentGene,

Thanks for the quick response.
> SilentGene: I suggest you assemble your reads independently suitable for your needs first. 

Thanks, I'll do that.

However, during DiTing process of mapping and normalization, uneven reads will be ignored (yet used during assembly) as the won't be into the `-r seqs/` directory, i.e., only paired or interleaved files will be used/processed. Am I right? 
I still do not know how to "rename" uneven files into `-r seqs/` directory for DiTing to be able to process both paired + uneven in a per-sample manner. 

I apologize if I'm being stubborn.
Thanks for shining a light on me on this @SilentGene.
I definitely appreciate the time you take reading this.

Cheers,
Mar.

**Comment by SilentGene** [comment]
Hi @MaryoHg , I don't think you should worry about the uneven reads in the mapping process. DiTing uses `bwa mem` to map reads, and `bwa mem` has its own strategy (i.e., setting a penalty) to deal with unpaired reads according to its manual. Therefore you can `cat` your paired reads with the unpaired reads into a single fastq file if you really want to keep the unpaired reads in your analyses. e.g.,:
```bash
$ cat sample_clean_1.fastq sample_unpaired_1.fastq > sample_1.fastq
$ cat sample_clean_2.fastq sample_unpaired_2.fastq > sample_2.fastq
```
Then you can put the `sample_1.fastq` and `sample_2.fastq` files into the folder which is invoked by the `-r` option.

I hope this makes sense to you.

Cheers,
Heyu

**Comment by MaryoHg** [comment]
Dear @SilentGene 

Thanks for your response and time. I'll give it a try.

Saludos,
Mar.
