### ISSUE TITLE
Normalization and relative abundance table

### ISSUE THREAD

**Issue by microfafa-gh** [xuechunxu/DiTing#33]
Hi team,

Awesome work! I have ran the pipeline on metagenome samples and got the relative abundance table. My results show pretty big numbers (123.2 for example) where I was expecting them to be on a relative abundance scale (0.02..). 
Any idea why this might be happening? The pipeline ran with no issues.
Thanks

**Comment by SilentGene** [comment]
Hi, Diting generates TPM values rather than percentages for better comparison across different samples. For more information about TPM, please refer to: https://www.rna-seqblog.com/rpkm-fpkm-and-tpm-clearly-explained/

Cheers,
H
