### ISSUE TITLE
Analysis of individual MAGs 

### ISSUE THREAD

**Issue by bharat1912** [xuechunxu/DiTing#9]
Hi 
Thank you for the software. I have used it for 3 environments and have not encountered any problems running diting.

I have several MAGS derived from fastq files (illumina) using  metawrap. I am trying to see if I can use the clean reads from my diting analysis using:
      $diting.py  -r path_to_CLEAN_READS -a  path to MAGS.fa  -o bin_diting

However, I am getting the following error:\
MAG_test/bin/bin_diting
2021-12-19 11:59:39 [INFO    ] **************[1/12] Check database***************
2021-12-19 11:59:39 [INFO    ] The KEGG database is set
2021-12-19 11:59:39 [INFO    ] The DMSP database is set
2021-12-19 11:59:39 [ERROR   ] Cannot find the corresponding reads for Pond_Bin28
NoneType: None

This is my MAG file:(partial)
>NODE_261_length_91528_cov_18.905535
CCATCGTTCACAACATTTTTTTGTGGCTCTGCAACTACTTAGGACAAAGCCCAAAAATTA
GTTGTGGATATAAGCAATGTTTGTAGTTTTATCATTATGTTGTAAAATACAACCACTATA
TAAAGTATGCATTATTTTTATCCTAATCTATTATGGTGGTTTGGTGTGTAGTTAGTAGGG
CGCGAAAAAGCATCTTTGTTTAAATATCTGTGTTTCAAGCATTTCTTTTAATGTCTTTTT
TAAAGGTTTTTTTTAGAAATTTTTAAATAGGATTGATTCTTTTTAGTTCTAATGATTGTT
TCAGTTATAGGGGTTGGCGCATTTGGTTATGCGTTGCTTTGTCATCTTGATAGAAAAAAT
GGGGTAAAAGATGCGCGAATTAAAGGTTCTAGTTCTCTTTTAAACAAAATTTCAAATCAG
GTTTCAGATAAATTTTCAGATAAATTTTCAGATAAATTTTCACATAAAGCATTTAACAAG
GTTTTTGAAGAGAGTGGTGAGAGTGGTTCTTATGAGCTCAGAGCTTTTGACGTGTTTCAA
GATGTGCTTTCTCATTTAAAAAAGGAGAGGTCTCACTTGTTTTTTCATAAAGGAGAAATG
ATTTCCGATACTGTCATGATTGCGAATTCATTAGAAGAAGCAGTTAAAGGAGCAGATGTA
ATTATTTTAGCTCTTAATTCAAGTTCCATAAGATCTGCTTTGAAGGATATAAAGCCTTTT
CTTAAGAGAAAAGTAATCATTGTCAATGTGTCAAAAGCATTAGAATCAGATACGGGTAAG
CCTATTTCAAGCATTTTTAAAGAAGAAACGCCTGAAGCAATTTACGTTGTTTTAGCAGGA

The following are the fastq sequence data files.
file.1.fastq
file 2.fastq 

The fastq has the following 
M00566:77:000000000-ATBW8:1:2106:16395:2191 1:N:0:ATGTCA
GTTCGGCGCTCAGCGCGTCGTATTCTCGGTCGGCATCCCTTTCGGCATGGGGGCCTACCAGTTGTCGCTTTTCGACGAGA
TCGCTTTTCGCATCTCGGCGCTTTTACCGACTCAGCGGTTTGCGATTGTGGCGTCTACGACGAACGGCATCTAATCGTGG
CCCGTCTCTCTTGCGATGTTTTCCGCGTCGAGCGCTCCAAAGGTTCGGGCGTATGACTTTCTTCGCGGTCTTCGCCCGCC
GACTGTCTCACTGACGGACTCCCTGCTCCATGCGACGACCTCGTTTGGCCCGCCTTCCTG
+
CCCC9+@+88B@EFGGGGE7F9CC6,<,6BFG>@+@@CC,:CCCFGGG,,,,+68,,:CFFGGGGF7DC,9,9+4BFE>+
DE+=,++9<+BFCFFFG+?+3@++,,::FGGEGGGC7+8@>+@C>FFGGGGG**5**<:>FGEGGD7<7<>,,?CEGGGD
GG<**1*+,77?FF**;8*++*231AE?EGG5CG**2*+3<CFFGGGGGE*1*;03<FGGGGGFGG**2/2C<;8CE8*:
**2**+++33<CGFFGC*2*2**0**2*96E7>)*.))1))01)75DF400>)0*)*0**
@M00566:77:000000000-ATBW8:1:2106:18334:2239 1:N:0:ATGTCA
GGCCGGAAGTTGATGTCGTCGGTCTTGTTCTTCACGCGGGTGAGGGTGTAGGCGCTGTCGAAGGCCACACTTCCTCCCAG
CCGGCGTCGCACGCTCACATTCTTTCCGTCGAACGTGCTGCGACCGGTGGATTCCTCCTGCTCAATCAGTCTGAACCCTC
CAGTCCCCCGCACGAGCGGCCTCGTCGCATCGGCCTCCCCCACCGAGCGTGTCACCCCGGCCGGAATCTTCGCGGGAGCA
TTGGTTTCGACCCGCCGCATGCCTTTGCGCCCGCGTGCCTGGACGTAGTCGACCCCAAGC

Can you help?  with the

**Comment by SilentGene** [comment]
Hi @bharat1912 , Diting is not designed for individual MAGs. However, you may get it run by treating your MAGs as metagenomic assemblies. By doing this, you need to rename your fastq reads according to your MAG names. For example, if you have a MAG named `Pond_Bin28`, the file name of your reads should be `Pond_Bin28_1.fastq` and `Pond_Bin28_2.fastq`.

**Comment by bharat1912** [comment]
Thanks. Response appreciated. Bharat.

**Comment by kunaljaani** [comment]
Hi @bharat1912,

I am facing an issue while running the diting.  It would be great help if you could please share your installation and running scripts?

Thanks,
Kunal
